services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: cityhive
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://cityhive:password@mongo:27017/
      RAILS_ENV: development
      RAILS_MAX_THREADS: 10
    depends_on:
      - db

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
